import type { KnipConfig } from "knip";

export default {
  // Scripts run via pnpm, plus src/env.ts, which SvelteKit loads by path in an
  // isolated Vite server (see experimental.explicitEnvironmentVariables) and
  // which therefore has no importer knip can follow.
  entry: ["scripts/**/*.ts", "src/env.ts"],

  // Icon sets consumed via @iconify/tailwind4 in CSS
  ignoreDependencies: ["@iconify-json/lucide", "@typescript/native"],

  // UI component library — sub-components are re-exported or used ad-hoc
  // Vendored agent skills, regenerated by `pnpm _db skills` on a drizzle bump.
  ignoreFiles: [
    "src/lib/components/ui/**/*.svelte",
    ".claude/**",
    ".agents/**",
  ],

  tailwind: {
    entry: ["tailwind.config.{js,cjs,mjs,ts}", "src/routes/layout.css"],
  },

  vite: {
    config: ["vite.config.{js,mjs,ts,cjs,mts,cts}"],
  },

  // Bundled in vite-plus, so knip can't auto-detect it
  oxlint: {
    config: [".oxlintrc.json", "oxlint.config.ts"],
  },

  // vitest is bundled inside vite-plus, so knip can't auto-detect it
  vitest: {
    config: ["vite.config.{js,ts}"],
    entry: ["src/**/*.test.ts", "src/test/setup.ts"],
  },
} satisfies KnipConfig;
